### ISSUE TITLE
security issue

### ISSUE THREAD

**Issue by alhaqhassan** [zrthxn/fileserver#1]
url "https://static.zrthxn.com/_upload" is open for every one, any one can upload any type of file of any size(no file validation). one can replace any file in the root  ("/home/zrthxn") by uploading file with same name.

**Comment by zrthxn** [comment]
Thanks for pointing that out. I didn't know anyone would go through this code. It was written very hastily. A few points
- I didn't think request validation was necessary when i wrote this but now I'll add that. 
- File size is not unchecked. It is limited by the reverse proxy on the server, so that's not an issue. 

I did not know about the **file replacement issue.** I realised it now that you pointed it out so thanks for that. Any idea how that can be handled? (besides just checking if the same filename exists and renaming)
